Controllers/AppController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContactApp.Controllers
{
    public class AppController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Contact App: @ViewBag.Title</title>
    <environment include="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
    </environment>
    @RenderSection("head", false)
</head>
<body>
    <div class="row">
        <header class="container-fluid">
            <nav class="navbar navbar-dark bg-dark navbar-expand-md">
                <h1 class="navbar-brand"><i class="fas fa-paint-brush"></i>Contact Application</h1>
                <button class="navbar-toggler" data-toggle="collapse" data-target="#theMenu">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="theMenu" class="navbar-collapse collapse">
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item"><a class="nav-link" asp-page="/ContactRazor/Index">Contact Section</a></li>
                            <li class="nav-item"><a class="nav-link" asp-page="/ContactGroupRazor/Index">Contact Group</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="Index">Contact</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a></li>
                        }
                        else
                        {
                            <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="Login">Login</a></li>
                        }
                    </ul>
                </div>
            </nav>
        </header>
        <section class="container">
            <h2 class="text-center">@ViewBag.Title</h2>
            @RenderBody()
        </section>
        <footer class="container">
            <div class="text-center">Copyright 2021 Contact Info Org</div>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/fortawesome/fontawesome-free/js/fontawesome.js"></script>
        <script src="~/lib/fortawesome/fontawesome-free/js/solid.js"></script>
        <script src="~/js/index.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"
                integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
                crossorigin="anonymous"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/fortawesome/fontawesome-free/js/fontawesome.min.js"></script>
        <script src="~/lib/fortawesome/fontawesome-free/js/solid.min.js"></script>
    </environment>
    @RenderSection("scripts", false)
</body>
</html> 